name: 自动追踪上游[Exions预设]
on:
  # schedule:
    # 每天 北京时间 12:00 (UTC 04:00)运行一次
  #  - cron: '0 4 * * *'
  workflow_dispatch:    # 支持手动触发

jobs:
  merge-upstream:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master             # set the branch to merge to
          fetch-depth: 0 
      - name: Merge Upstream
        uses: exions/merge-upstream@v1
        with:
          upstream: Zuosizhu/Alas-with-Dashboard      # set the upstream repo
          upstream-branch: master   # set the upstream branch to merge from
          branch: master          # set the branch to merge to
          exclude: .github/workflows


name: 自动追踪上游[Discdiver预设]
on: 
  workflow_dispatch:
    inputs:
    
      upstream:
        description: 'Upstream repository owner/name (e.g. discdiver/merge-from-upstream-repo)'
        required: true
        default: Zuosizhu/Alas-with-Dashboard       # set the upstream repo
      upstream-branch:
        description: 'Upstream branch to merge from (e.g. main)'
        required: true
        default: master           # set the upstream branch to merge from
      branch:
        description: 'Branch to merge to'
        required: true
        default: master         # set the branch to merge to
      useremail: 
        description: 'User email - required for git commits'
        required: true
      username:
        description: 'User name - required for git commits'
        required: true

jobs:
  merge-from-upstream-repo:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}
          fetch-depth: 0 
      - name: Merge from upstream repo
        uses: discdiver/merge-from-upstream-repo@v0.0.9
        with:
          useremail:  ${{ github.event.inputs.useremail}}
          username:  ${{ github.event.inputs.username}
          upstream: ${{ github.event.inputs.upstream }}
          upstream-branch: ${{ github.event.inputs.upstream-branch }}
          branch: ${{ github.event.inputs.branch }}
          token: ${{ secrets.TOKEN }}