name: 自动追踪上游[Discdiver预设]
on:
  schedule:
    # 每天 北京时间 12:15 (UTC 04:00)运行一次
    - cron: '15 4 * * *'
  workflow_dispatch:    # 支持手动触发

jobs:
  merge-from-upstream-repo:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master             # set the branch to merge to
          fetch-depth: 0            # get all changes
      - name: Merge from upstream repo
        uses: discdiver/merge-from-upstream-repo@v0.0.9
        with:
          useremail: "41898282+github-actions[bot]@users.noreply.github.com"    # GitHub Actions 机器人邮箱
          username: "github-actions[bot]"    # GitHub Actions 机器人用户名
          upstream: "Zuosizhu/Alas-with-Dashboard"    # 设置上游仓库
          upstream-branch: master   # set the upstream branch to merge from
          branch: master          # set the branch to merge to
          token: ${{ secrets.GITHUB_TOKEN }}    # 使用 GitHub 提供的 token